development:
  S3_BUCKET_NAME: kozmedia
  AWS_ACCESS_KEY_ID: AKIAIFI72ZXPTH4AAEUA
  AWS_SECRET_ACCESS_KEY: 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

production:
  SECRET_KEY_BASE: randhkjfsldhkjfhsdkfhsdfdcomecrapshere
  S3_BUCKET_NAME: kozmedia
  AWS_ACCESS_KEY_ID: AKIAIFI72ZXPTH4AAEUA
  AWS_SECRET_ACCESS_KEY: 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